FROM nvcr.io/nvidia/cuda:11.0.3-devel-ubuntu20.04

RUN apt-get update && apt-get upgrade -y && apt-get clean

ENV DEBIAN_FRONTEND=noninteractive

ENV TZ=America/New_York

RUN apt-get install -y --no-install-recommends \
    wget \
    pkg-config \
    build-essential \
    cmake \
    git \
    openssh-client \
    curl \
    vim-gtk \
    tmux \
    zip \
    unzip \
    libjpeg-dev \
    libopenexr-dev \
    libpng-dev \
    sudo \
    python3 \
    python3-pip \
    python3-dev \
    python3-tk \
    python3-pil.imagetk \
    python3-setuptools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --no-cache-dir --upgrade pip

RUN python3 -m pip install --no-cache-dir \
    pytorch-forecasting==1.0.0 \
    termcolor==2.4.0 \
    pyyaml==6.0.2 \
    pandas==2.0.3

CMD ["bash"]